# Generated by Django 4.2.3 on 2023-09-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number1',
            new_name='phone_number_1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number2',
            new_name='phone_number_2',
        ),
    ]
